package errcode

var shortDescriptions = map[ErrorCode]string{
	ErrorCode(0x00): "No error",
	ErrorCode(0x01): "Verification failure",
	ErrorCode(0x02): "Wrong key length",
	ErrorCode(0x04): "Invalid key type code",
	ErrorCode(0x05): "Invalid key length",
	ErrorCode(0x10): "Source key parity error",
	ErrorCode(0x11): "Destination key parity error",
	ErrorCode(0x12): "User storage not available",
	ErrorCode(0x13): "Invalid LMK ID",
	ErrorCode(0x14): "Invalid PIN under LMK 02-03",
	ErrorCode(0x15): "Invalid input data",
	ErrorCode(0x16): "Console or printer not ready or not connected",
	ErrorCode(0x17): "HSM not authorized",
	ErrorCode(0x18): "Document format definition not loaded",
	ErrorCode(0x19): "Invalid Diebold Table",
	ErrorCode(0x20): "PIN block does not contain valid values",
	ErrorCode(0x21): "Index out of bounds",
	ErrorCode(0x22): "Invalid account number",
	ErrorCode(0x23): "Invalid PIN block format code",
	ErrorCode(0x24): "PIN length not 4-12",
	ErrorCode(0x25): "Decimalization Table error",
	ErrorCode(0x26): "Invalid key scheme",
	ErrorCode(0x27): "Incompatible key length",
	ErrorCode(0x28): "Invalid key type",
	ErrorCode(0x29): "Key function not permitted",
	ErrorCode(0x30): "Invalid reference number",
	ErrorCode(0x31): "Insufficient solicitation entries for batch",
	ErrorCode(0x32): "LIC007 (AES) not installed",
	ErrorCode(0x33): "LMK key change storage is corrupted",
	ErrorCode(0x39): "Fraud detection",
	ErrorCode(0x40): "Invalid checksum",
	ErrorCode(0x41): "Internal hardware/software error",
	ErrorCode(0x42): "DES failure",
	ErrorCode(0x43): "RSA Key Generation Failure",
	ErrorCode(0x46): "Invalid tag for encrypted PIN",
	ErrorCode(0x47): "Algorithm not licensed",
	ErrorCode(0x49): "Private key error",
	ErrorCode(0x51): "Invalid message header",
	ErrorCode(0x65): "Transaction Key Scheme set to None",
	ErrorCode(0x67): "Command not licensed",
	ErrorCode(0x68): "Command has been disabled",
	ErrorCode(0x69): "PIN block format disabled",
	ErrorCode(0x74): "Invalid digest info syntax",
	ErrorCode(0x75): "Single length key masquerading as double or triple length",
	ErrorCode(0x76): "RSA public key/data length error",
	ErrorCode(0x77): "Clear data block error",
	ErrorCode(0x78): "Private key length error",
	ErrorCode(0x79): "Hash algorithm object identifier error",
	ErrorCode(0x80): "Data length error (MAC)",
	ErrorCode(0x81): "Invalid certificate header",
	ErrorCode(0x82): "Invalid check value length",
	ErrorCode(0x83): "Key block format error",
	ErrorCode(0x84): "Key block check value error",
	ErrorCode(0x85): "Invalid OAEP Mask Generation Function",
	ErrorCode(0x86): "Invalid OAEP MGF Hash Function",
	ErrorCode(0x87): "OAEP Parameter Error",
	ErrorCode(0x90): "Data parity error",
	ErrorCode(0x91): "LRC does not match",
	ErrorCode(0x92): "Count value out of bounds",
	ErrorCode(0xA1): "Incompatible LMK schemes",
	ErrorCode(0xA2): "Incompatible LMK identifiers",
	ErrorCode(0xA3): "Incompatible key block LMK identifiers",
	ErrorCode(0xA4): "Key block authentication failure",
	ErrorCode(0xA5): "Incompatible key length",
	ErrorCode(0xA6): "Invalid key usage",
	ErrorCode(0xA7): "Invalid algorithm",
	ErrorCode(0xA8): "Invalid mode of use",
	ErrorCode(0xA9): "Invalid key version number",
	ErrorCode(0xAA): "Invalid export field",
	ErrorCode(0xAB): "Invalid number of optional blocks",
	ErrorCode(0xAC): "Optional header block error",
	ErrorCode(0xAD): "Key status optional block error",
	ErrorCode(0xAE): "Invalid start date/time",
	ErrorCode(0xAF): "Invalid end date/time",
	ErrorCode(0xB0): "Invalid encryption mode",
	ErrorCode(0xB1): "Invalid authentication mode",
	ErrorCode(0xB2): "Misc key block error",
	ErrorCode(0xB3): "Invalid number of optional blocks",
	ErrorCode(0xB4): "Optional block data error",
	ErrorCode(0xB5): "Incompatible components",
	ErrorCode(0xB6): "Incompatible key status optional blocks",
	ErrorCode(0xB7): "Invalid change field",
	ErrorCode(0xB8): "Invalid old value",
	ErrorCode(0xB9): "Invalid new value",
	ErrorCode(0xBA): "No key status block in the key block",
	ErrorCode(0xBB): "Invalid wrapping key",
	ErrorCode(0xBC): "Repeated optional block",
	ErrorCode(0xBD): "Incompatible key types",
	ErrorCode(0xBE): "Invalid key block header ID",
}

var longDescriptions = map[ErrorCode]string{
	ErrorCode(0x00): "No error",
	ErrorCode(0x01): "Verification failure or warning of imported key parity error",
	ErrorCode(0x02): "Key inappropriate length for algorithm",
	ErrorCode(0x04): "Invalid key type code",
	ErrorCode(0x05): "Invalid key length flag",
	ErrorCode(0x10): "Source key parity error",
	ErrorCode(0x11): "Destination key parity error or key all zeros",
	ErrorCode(0x12): "Contents of user storage not available. Reset, power-down or overwrite",
	ErrorCode(0x13): "Invalid LMK Identifier",
	ErrorCode(0x14): "PIN encrypted under LMK pair 02-03 is invalid",
	ErrorCode(0x15): "Invalid input data (invalid format, invalid characters, or not enough data provided)",
	ErrorCode(0x16): "Console or printer not ready or not connected",
	ErrorCode(0x17): "HSM not authorized, or operation prohibited by security settings",
	ErrorCode(0x18): "Document format definition not loaded",
	ErrorCode(0x19): "Specified Diebold Table is invalid",
	ErrorCode(0x20): "PIN block does not contain valid values",
	ErrorCode(0x21): "Invalid index value, or index/block count would cause an overflow condition",
	ErrorCode(0x22): "Invalid account number",
	ErrorCode(0x23): "Invalid PIN block format code. (Use includes where the security setting to implement PCI HSM limitations on PIN Block format usage is applied, and a Host command attempts to convert a PIN Block to a disallowed format.)",
	ErrorCode(0x24): "PIN is fewer than 4 or more than 12 digits in length",
	ErrorCode(0x25): "Decimalization Table error",
	ErrorCode(0x26): "Invalid key scheme",
	ErrorCode(0x27): "Incompatible key length",
	ErrorCode(0x28): "Invalid key type",
	ErrorCode(0x29): "Key function not permitted",
	ErrorCode(0x30): "Invalid reference number",
	ErrorCode(0x31): "Insufficient solicitation entries for batch",
	ErrorCode(0x32): "LIC007 (AES) not installed",
	ErrorCode(0x33): "LMK key change storage is corrupted",
	ErrorCode(0x39): "Fraud detection",
	ErrorCode(0x40): "Invalid checksum",
	ErrorCode(0x41): "Internal hardware/software error: bad RAM, invalid error codes, etc.",
	ErrorCode(0x42): "DES failure",
	ErrorCode(0x43): "RSA Key Generation Failure",
	ErrorCode(0x46): "Invalid tag for encrypted PIN",
	ErrorCode(0x47): "Algorithm not licensed",
	ErrorCode(0x49): "Private key error, report to supervisor",
	ErrorCode(0x51): "Invalid message header",
	ErrorCode(0x65): "Transaction Key Scheme set to None",
	ErrorCode(0x67): "Command not licensed",
	ErrorCode(0x68): "Command has been disabled",
	ErrorCode(0x69): "PIN block format has been disabled",
	ErrorCode(0x74): "Invalid digest info syntax (no hash mode only)",
	ErrorCode(0x75): "Single length key masquerading as double or triple length key",
	ErrorCode(0x76): "RSA public key length error or RSA encrypted data length error",
	ErrorCode(0x77): "Clear data block error",
	ErrorCode(0x78): "Private key length error",
	ErrorCode(0x79): "Hash algorithm object identifier error",
	ErrorCode(0x80): "Data length error. The amount of MAC data (or other data) is greater than or less than the expected amount.",
	ErrorCode(0x81): "Invalid certificate header",
	ErrorCode(0x82): "Invalid check value length",
	ErrorCode(0x83): "Key block format error",
	ErrorCode(0x84): "Key block check value error",
	ErrorCode(0x85): "Invalid OAEP Mask Generation Function",
	ErrorCode(0x86): "Invalid OAEP MGF Hash Function",
	ErrorCode(0x87): "OAEP Parameter Error",
	ErrorCode(0x90): "Data parity error in the request message received by the HSM",
	ErrorCode(0x91): "Longitudinal Redundancy Check (LRC) character does not match the value computed over the input data (when the HSM has received a transparent async packet)",
	ErrorCode(0x92): "The Count value (for the Command/Data field) is not between limits, or is not correct (when the HSM has received a transparent async packet)",
	ErrorCode(0xA1): "Incompatible LMK schemes",
	ErrorCode(0xA2): "Incompatible LMK identifiers",
	ErrorCode(0xA3): "Incompatible key block LMK identifiers",
	ErrorCode(0xA4): "Key block authentication failure",
	ErrorCode(0xA5): "Incompatible key length",
	ErrorCode(0xA6): "Invalid key usage",
	ErrorCode(0xA7): "Invalid algorithm",
	ErrorCode(0xA8): "Invalid mode of use",
	ErrorCode(0xA9): "Invalid key version number",
	ErrorCode(0xAA): "Invalid export field",
	ErrorCode(0xAB): "Invalid number of optional blocks",
	ErrorCode(0xAC): "Optional header block error",
	ErrorCode(0xAD): "Key status optional block error",
	ErrorCode(0xAE): "Invalid start date/time",
	ErrorCode(0xAF): "Invalid end date/time",
	ErrorCode(0xB0): "Invalid encryption mode",
	ErrorCode(0xB1): "Invalid authentication mode",
	ErrorCode(0xB2): "Miscellaneous key block error",
	ErrorCode(0xB3): "Invalid number of optional blocks",
	ErrorCode(0xB4): "Optional block data error",
	ErrorCode(0xB5): "Incompatible components",
	ErrorCode(0xB6): "Incompatible key status optional blocks",
	ErrorCode(0xB7): "Invalid change field",
	ErrorCode(0xB8): "Invalid old value",
	ErrorCode(0xB9): "Invalid new value",
	ErrorCode(0xBA): "No key status block in the key block",
	ErrorCode(0xBB): "Invalid wrapping key",
	ErrorCode(0xBC): "Repeated optional block",
	ErrorCode(0xBD): "Incompatible key types",
	ErrorCode(0xBE): "Invalid key block header ID",
}
